### ISSUE TITLE
运行demo1报错

### ISSUE THREAD

**Issue by aymonYU** [wechat-miniprogram/kbone#1]
````

/Users/aymonyu/tencent/test/kbone/examples/demo1/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'webpack-sources'
```
npm i webpack-sources -S
还是报错

**Comment by LarenDorr** [comment]
https://github.com/wechat-miniprogram/kbone/blob/master/examples/demo1/build/webpack.mp.config.js#L7
把这个`mp-webpack-plugin`改为npm包，然后`npm i mp-webpack-plugin`

**Comment by aymonYU** [comment]
最好添加一个项目包管理的工具，例如lerna，这样就解决一个仓库管理过个包的关联性问题

**Comment by JuneAndGreen** [comment]
这是因为 packages/mp-webpack-plugin 下没有跑过 npm install，所以寻找依赖就直接从全局包中寻找导致。现在 demo 已经换成正式的依赖包，不使用相对路径了。
