### ISSUE TITLE
使用内置组件写起来很不舒服

### ISSUE THREAD

**Issue by chenjigeng** [wechat-miniprogram/kbone#11]
开始使用的时候，觉得内置组件写起来很不舒服。
目前我在开发小程序，每次我在写html/wxml标签的时候，我都会在想，我写的这个标签会不会被转化为其他标签？比如我写span，会不会被渲染为text组件。我写img，会不会被渲染为image。这个时候我就得查一下开发指南看一遍。
既然不确定，那我就统一写wx-component吧。
可是又没有类型提示。我不知道behavior有哪些选项。填了behavior后，能传的属性值、方法名也没有代码提示。写起来就很难受。
想看下这里有没有什么比较好的解决方案？

**Comment by JuneAndGreen** [comment]
一般来说以同构的方式开发，使用内置组件的场景本身应该不会太多才对。比如 div、span、img 应该不需要关心会被渲染成小程序的什么内置组件吧，对于 Web 标签是尽量兼容成 Web 端的表现的。只有个别组件比如 live-player 等 Web 端是没有对应标签的才会使用 wx-component，想知道有哪些场景是需要大量的 wx-component 的？

**Comment by chenjigeng** [comment]
目前我是单纯想用来开发小程序，就会遇到这个问题。

**Comment by chenjigeng** [comment]
@JuneAndGreen 其实我有个想法。因为小程序的标签和web的标签基本都是不同的（除了button)。那么是不是允许让使用者直接使用小程序的标签呢。
比如我写text、scroll-view，这些东西web都是没有的。使用的人肯定也知道这些是小程序专有的，使用后h5肯定不能使用。而且这些标签你们应该也是可以识别的，顶多再底层做一层转译为wx-component的语法？（这里我没仔细看代码不好评估改动量）
这样对使用者来说，他大部分情况都不需要考虑“我能不能直接写这个标签，我写这个标签会被转译成什么样子”。
至少这样对于开发小程序的人来说，更加友好，而且对web或者同构开发的同学也没有什么影响。

**Comment by JuneAndGreen** [comment]
@chenjigeng 明白你的诉求，但是直接用小程序标签名可能会有冲突，如果用 wx-live-player 这样的写法能否满足呢？（使用 wx- 前缀表示小程序内置组件）

**Comment by chenjigeng** [comment]
@JuneAndGreen 我上面有说，目前小程序的标签跟web标签重合，就我所知就是button和input。input你们目前好像已经会区分web和小程序来渲染不同的组件。我觉得button是不是也可以？
既然重合度这么低，为什么不直接允许用小程序的标签呢？

**Comment by JuneAndGreen** [comment]
@chenjigeng button 因为两者差异比较大，所以没有直接替换（button 支持 open-type 和 type，所以比较特殊）。另外像label虽然有同名，但是不支持跨 shadow-tree 所以没法直接替换。

直接使用小程序标签有个很大的问题就是容易与 html 的标签混淆，虽然重合度低，但是 web 端是没有小程序组件的，所以如果要支持还是需要个明显的区分（比如 wx- 前缀）

另外就算只用于开发小程序，应该大部分还是像 div、span、input、a 这样的写法的吧，不需要强行使用 view/text 等内置组件的写法，除非有内置组件某些特性方面的需求。

**Comment by chenjigeng** [comment]
@JuneAndGreen 我觉得正因为web没有小程序的这些标签的困扰，所以使用者用这些标签可以明显的知道这个写法只会用于小程序，也只有小程序开发的时候会用到这些。

**Comment by JuneAndGreen** [comment]
“使用者用这些标签可以明显的知道这个写法只会用于小程序”，你应该是只想用内置组件的写法吧。这个方案是以按照 web 的方式来编写多端代码为初衷，也就是说出发点是要考虑 web 端标签和内置组件混用的情况，在同构和协作开发的场景下需要有区分才不会引起困扰（比如代码里有一个 picker，得判断是否 web 标签还是 vue 组件还是内置组件），所以后面可以提供方法支持用户选择哪种写法，但是应该不会将直接使用标签作为推荐做法。

另外建议直接使用 web 标签来编写应用。比如上面提到的可以直接写成 div、span、img 这些 web 标签的，不建议直接写成 view、text、image，不然一些性能上的优化会应用不上（因为直接使用内置组件的情况都会被抽象成一个自定义组件）。

**Comment by dntzhang** [comment]
> 其实我有个想法。因为小程序的标签和web的标签基本都是不同的（除了button)。那么是不是允许让使用者直接使用小程序的标签呢。
比如是否允许直接写text、scroll-view这些小程序标签。因为这些东西web都是没有的，使用的人肯定也知道这些是小程序专有的，使用后h5肯定不能使用。
实现上来说的话，这些标签你们应该也是可以识别的，顶多再底层做一层转译为wx-component的语法？（这里我没仔细看代码不好评估改动量）
这样对使用者来说，大部分情况都不需要考虑“我能不能直接写这个标签，我写这个标签会被转译成什么样子”。
至少这样对于开发小程序的人来说，更加友好，而且对web或者同构开发的同学也没有什么影响。


好建议！  @chenjigeng

**Comment by JuneAndGreen** [comment]
增加了一个 runtime.wxComponent 配置，默认支持 wx-component 和 wx- 前缀写法，值为 noprefix 表示在前面两种写法都支持的前提下，还支持无前缀写法。

PS：view、text、image 这三个可能会大面积使用的内置组件建议使用 div、span、img 替代，因为当前针对 div、span、img 是做过子树优化的，而 view、text、image 则和其他内置组件同样的渲染方式，没有做特殊优化。
