### ISSUE TITLE
多页面可以支持单个入口吗?

### ISSUE THREAD

**Issue by scutcl** [wechat-miniprogram/kbone#13]
vue-router可以支持多页面吗？

**Comment by JuneAndGreen** [comment]
不是很理解问题，是使用 vue-router 搭一个 spa 么？如果是的话是支持的，可以参考这个demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo1

**Comment by scutcl** [comment]
> 不是很理解问题，是使用 vue-router 搭一个 spa 么？如果是的话是支持的，可以参考这个demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo1

小程序一般都是多页应用呀，如果按照demo5的写法，就需要写很多入口

**Comment by JuneAndGreen** [comment]
是的，支持多页，然后每个页面里面也支持单页的做法（比如使用 vue-router）。

**Comment by dntzhang** [comment]
@JuneAndGreen 个人建议单页里不再使用 router，不然多页又嵌套多页没有必要 =  =！

**Comment by JuneAndGreen** [comment]
@dntzhang 小程序多页的一个好处是可以用于后续规划中的分包功能的，分包可以按页划分。

不过单页里是否要用到 router 就得开发自己视情况而定了，能力上是支持的，单页里使用 router 可以使用 url 来管理这个页面内各个模块的展示隐藏。当然，开发者也可以选择不用的。

**Comment by dntzhang** [comment]
以后路由分包不知道 react 里怎么用。

而且分包合理的方式是以动态 import ()为分包，而不是路由。

**Comment by JuneAndGreen** [comment]
@dntzhang 确实是按照 import() 来做更合理些，不过小程序的分包是按小程序页面维度的，因为这个限制，目前来看无论是按路由还是按 import() 来做分包好像都没有一个可行的方案。所以分包的规划暂时只能应用在多页的项目中。
