### ISSUE TITLE
vue-cli-plugin-kbone

### ISSUE THREAD

**Issue by scutcl** [wechat-miniprogram/kbone#15]
可以自定义配置文件路径吗？

**Comment by scutcl** [comment]
多页面怎么写呢

**Comment by JuneAndGreen** [comment]
目前这个插件还未支持多页面。

vue-cli-plugin-kbone 还不完善，所以目前是还没有在文档上说明的。后面会对这个插件进行一次优化，建议目前先采用手写 webpack 配置的方式来开发。

**Comment by JuneAndGreen** [comment]
vue-cli-plugin-kbone@0.4.0 对多入口进行了支持，具体可参考demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo4

多入口要求在项目根目录下提供 vue.config.js，其中必须有 pages 字段：https://cli.vuejs.org/zh/config/#pages
