### ISSUE TITLE
tabBar怎么实现

### ISSUE THREAD

**Issue by scutcl** [wechat-miniprogram/kbone#16]
原生的tabBar在vue-cli-plugin-kbone怎么使用

**Comment by JuneAndGreen** [comment]
tabBar 按照当前计划是预计9月中旬支持到。而 vue-cli-plugin-kbone 的问题同： #15

**Comment by JuneAndGreen** [comment]
tabBar 已支持，参考 demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo9

* miniprogram-render 更新至 0.1.3 或以上版本
* mp-webpack-plugin 更新至 0.1.2 或以上版本
