### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by smartapp-ep** [wechat-miniprogram/kbone#21]
hey, 

firstly this is a great framework!

I'd like to query about i18n support. eg. can vue-i18n be used then auto converted to  miniprogram-i18n compatible? what's the road map? or what's the recommended way?

thanks in advance!

**Comment by JuneAndGreen** [comment]
thx for appreciation! this feature now is in the plan, we are thinking about how to implement it.

**Comment by JuneAndGreen** [comment]
vue-i18n demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo14
