### ISSUE TITLE
支付等原生sdk该怎么用

### ISSUE THREAD

**Issue by ZhangYunP** [wechat-miniprogram/kbone#24]
假如用kbone开发小程序，当我有支付之类的业务逻辑该怎处理？在vue中调h5支付还是直接调小程序支付？

**Comment by JuneAndGreen** [comment]
可以通过 process.env.isMiniprogram 来判断所处环境，小程序端仍然调 wx.requestPayment，h5 则走原本 h5 的逻辑。
