### ISSUE TITLE
vue+kbone如何适配微信H5和小程序？

### ISSUE THREAD

**Issue by lzm20** [wechat-miniprogram/kbone#26]
你好，你在研究vue+kbone中是如何做手机微信H5和小程序适配的？我之前采用的是微信H5用flexible+px转rem适配的，小程序是750rpx做的。现在有什么方法vue+kbone构建H5和小程序中，两者样式都能够正常显示？

**Comment by lzm20** [comment]
{
                test: /\.css$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    'px2rpx-loader?rpxUnit=1'
                ],
            }

**Comment by JuneAndGreen** [comment]
现在 px 仍然是可以正常使用的，rem 需要基础库支持某个特性，这个在近期版本会支持上。

**Comment by JuneAndGreen** [comment]
[edd9efc](https://github.com/wechat-miniprogram/kbone/commit/edd9efcfc8ec95f9e4ed03f4cc5766d28743e13d)  已支持 rem，基于基础库 2.9.0
