### ISSUE TITLE
Preact X

### ISSUE THREAD

**Issue by b2nil** [wechat-miniprogram/kbone#28]
Preact v10.0.0 已经正式发布了，kbone 可以支持 preact x 了吗？

**Comment by dntzhang** [comment]
我这几天支持下。preact x 很棒~

**Comment by b2nil** [comment]
期待中……^_-

**Comment by dntzhang** [comment]
刚提交了一版， https://github.com/Tencent/omi/commit/dc674317dc672f5d0b59ac7dc6593c5d1e26e609 。剩两个兼容性问题需要 kbone 适配

**Comment by dntzhang** [comment]
https://github.com/dntzhang/kbone-template-preact

ok了，已经 pr

**Comment by b2nil** [comment]
试跑了模板，正常。 
改用 `hooks` 跑了一下，正常。
