### ISSUE TITLE
vue+kbone构建小程序，摁手机的物理键返回退出小程序？

### ISSUE THREAD

**Issue by lzm20** [wechat-miniprogram/kbone#30]

**Comment by JuneAndGreen** [comment]
如果是只有一个页面的话，按物理返回键是退出小程序，这是小程序本身的逻辑，无法 hack，所以如果需要按物理返回键返回上一个页面，必须是在多页且当前页不是第一页的情况下才行。

**Comment by JuneAndGreen** [comment]
参考问答：https://developers.weixin.qq.com/community/develop/doc/000e6c0ca548f8b914599d8bd56c00
