### ISSUE TITLE
我安装了插件mint-ui，构建小程序之后报错，是什么原因呢？

### ISSUE THREAD

**Issue by lzm20** [wechat-miniprogram/kbone#32]
报错Cannot read property 'toLowerCase' of undefined;at "pages/index/index" page lifeCycleMethod onLoad function

**Comment by JuneAndGreen** [comment]
给下下报错的调用栈看看，toLowerCase 是从哪个地方抛出来的？

**Comment by TomVista** [comment]
![image](https://user-images.githubusercontent.com/42435611/70512165-b9729900-1b6a-11ea-90c7-6cd73b22e500.png)

**Comment by JuneAndGreen** [comment]
这个报错已经修复，不过因为 Web 端部分接口无法在小程序实现兼容，所以可能部分组件使用会有点问题（比如属性选择器、getCompultedStyle 等），这里推荐使用 kbone-ui：https://github.com/wechat-miniprogram/kbone-ui ，兼容 web 端和小程序端。
