### ISSUE TITLE
支持支付宝、百度等平台吗？

### ISSUE THREAD

**Issue by tangshuang** [wechat-miniprogram/kbone#34]
一般来说，开发小程序，肯定希望一次写码，简单处理之后，就可以编译到多端去用，这应该也是商家的一个期望，不知道 kbone 是否支持微信之外的其他小程序平台？

**Comment by JuneAndGreen** [comment]
因为这里是基于微信小程序基础库的某些特性来实现的，在不了解其他平台的规划实现情况下是不会主动去兼容其他平台。
