### ISSUE TITLE
[Bug Report] Error: Component is not found in path "pages/home/miniprogram-element" (using by "pages/home/index")

### ISSUE THREAD

**Issue by ly525** [wechat-miniprogram/kbone#35]
```js
VM271:1 Error: Component is not found in path "pages/home/miniprogram-element" (using by "pages/home/index")
    at K (WAService.js:1)
    at K (WAService.js:1)
    at WAService.js:1
    at Module.Fe (WAService.js:1)
    at Function.value (WAService.js:1)
    at Et (WAService.js:1)
    at o (WAService.js:1)
    at WAService.js:1
    at WAService.js:1
    at WAService.js:1
```

1. 使用脚手架进行初始化  `kbone init my-app(vue) && yarn && npm run mp`
2. 遇到 #4  里面的问题，通过安装 `cd dist/mp && npm install --save miniprogram-render` 模块 &&  `构建 npm && 编译` 解决
3. 但是会出现上面的问题，通过 Google 进行了搜索，没有找到合适的回答，所以想麻烦作者，帮忙看下，非常感谢。

附上截图，再次感谢
> ![image](https://user-images.githubusercontent.com/12668546/67654060-395fed80-f987-11e9-819a-36ae1244e999.png)

**Comment by JuneAndGreen** [comment]
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html  参考这个文档来使用 npm 组件，有两个会经常被遗漏的地方：
1、基础库需要版本 2.2.1 或以上、开发者工具需要 1.02.1808300 或以上
2、本地配置里是否有勾选 “使用 npm 模块”

看看这两个点是否符合？

**Comment by ly525** [comment]
嗯，已经检查。我下载了vue模板项目，重新运行了，没有这个问题了。非常感谢, 有问题的话，再请教

**Comment by eyea** [comment]
我遇到一个同样的问题 JuneAndGreen同学提到符合，如图:
![image](https://user-images.githubusercontent.com/17020223/76431053-09702e80-63ec-11ea-98d1-e33fe54ab037.png)

===
![image](https://user-images.githubusercontent.com/17020223/76431075-12610000-63ec-11ea-984c-04537e7fd7dc.png)

===
![image](https://user-images.githubusercontent.com/17020223/76431103-1c82fe80-63ec-11ea-8333-e4de7c85d4d8.png)

===
但是仍然存在问题:

![image](https://user-images.githubusercontent.com/17020223/76431242-49371600-63ec-11ea-8f14-23802cb344e9.png)

**Comment by JuneAndGreen** [comment]
@eyea 还有一种可能，工具没有监听到文件变化导致，通常是开了工具后再跑 npm install 再进行 npm 构建可能复现。这种可以尝试一下重启工具，一般可以得到解决。

**Comment by eyea** [comment]
@JuneAndGreen 感谢回答，已经处理好了。
