### ISSUE TITLE
how to minify generated files?

### ISSUE THREAD

**Issue by frustigor** [wechat-miniprogram/kbone#36]
在 optimization.minimizer 中使用 TerserJSPlugin OptimizeCSSAssetsPlugin 进行压缩，common 文件夹下面的 main.js 等都进行了压缩，但是插件生成的 app.js pages/index.wxss 这些都没有压缩，请问应该怎么处理？

**Comment by JuneAndGreen** [comment]
目前插件这里还没有提供相关配置，这些可以直接通过工具的压缩功能来做。

![image](https://user-images.githubusercontent.com/7931744/67691494-a8fec880-f9d9-11e9-8c6e-59a0aede625a.png)
