### ISSUE TITLE
偶尔出现Uncaught Error: module "pages/index/miniprogram-render.js" is not defined

### ISSUE THREAD

**Issue by easonjim** [wechat-miniprogram/kbone#4]
```js
Uncaught Error: module "pages/index/miniprogram-render.js" is not defined
    at require (VM956 WAService.js:19)
    at VM956 WAService.js:19
    at index.js:1
    at require (VM956 WAService.js:19)
    at <anonymous>:11:7
    at HTMLScriptElement.scriptLoaded (appservice?t=1564448406408:2221)
    at HTMLScriptElement.script.onload (appservice?t=1564448406408:2233)
```
编译运行时出现了这个错误

**Comment by stephenml** [comment]
这个是因为文件发生变化，开发者工具没有监听到新文件导致的，应该是工具的问题

**Comment by easonjim** [comment]
@stephenml 已经升级了最新版的开发者工具

**Comment by stephenml** [comment]
我也有同样的问题，已经反馈给他们了

**Comment by JuneAndGreen** [comment]
这个应该是工具监听文件变更时有点问题，导致自动编译时没有注入到新构建的 npm 包，可以在社区提个帖，届时会有工具那边的同学来进行跟进。

**Comment by easonjim** [comment]
看来这个问题无解：
![image](https://user-images.githubusercontent.com/5625433/62268866-d8964700-b463-11e9-92f1-f42d02126859.png)

**Comment by JuneAndGreen** [comment]
@easonjim 给下帖子链接？我直接找下负责工具的开发同学问问。

**Comment by easonjim** [comment]
@JuneAndGreen 
[微信开放社区地址](https://developers.weixin.qq.com/community/develop/doc/0000ced3738090a40af8c760b5c800?jumpto=comment&commentid=000e4acb8680109500f85a2c1544)
非常的感谢

**Comment by yangruru** [comment]
我也出现了这个问题，并且重新编译也不行，不是偶现，是必现。有人解决了吗？急等大佬回复中。。。

**Comment by TomVista** [comment]
![image](https://user-images.githubusercontent.com/42435611/65402810-47a87000-de03-11e9-9011-b4219f8bfb91.png)

**Comment by xmsz** [comment]
这个问题可能和开发者工具有关

不知道什么情况下会触发，触发以后，无论怎么构建或者重新安装都会显示Uncaught Error: module "pages/home/miniprogram-render" is not defined 

为什么推测是开发者工具相关，是因为
如果我把 out 目录改为其他目录，然后重新导入就没问题..

然后我把一模一样的代码复制到原来不能运行的目录，还是报错

没有进一步测试，不知道什么原因，太耗时间了。只能先用别的目录

**Comment by xmsz** [comment]
> 这个问题可能和开发者工具有关
> 
> 不知道什么情况下会触发，触发以后，无论怎么构建或者重新安装都会显示Uncaught Error: module "pages/home/miniprogram-render" is not defined
> 
> 为什么推测是开发者工具相关，是因为
> 如果我把 out 目录改为其他目录，然后重新导入就没问题..
> 
> 然后我把一模一样的代码复制到原来不能运行的目录，还是报错
> 
> 没有进一步测试，不知道什么原因，太耗时间了。只能先用别的目录
> 
> 底下是出现 bug 的目录构建的
> 
> ![image](https://user-images.githubusercontent.com/5879146/75147001-4921ef80-5737-11ea-8480-3860df00ed8f.png)
> 
> ![image](https://user-images.githubusercontent.com/5879146/75147021-550db180-5737-11ea-8064-d4bbfa25c83f.png)

把开发者工具的缓存清掉，然后重新打开可以，所以确定就是开发者工具缓存问题
