### ISSUE TITLE
不支持支付宝小程序，差评

### ISSUE THREAD

**Issue by 1120040377** [wechat-miniprogram/kbone#41]

**Comment by JuneAndGreen** [comment]
这是利用了微信小程序自身的一些特性来实现的，如果其他的一些小程序没有实现这些特性那我们也无能为力了。

**Comment by qiuziz** [comment]
现在市面上其他小程序基本上与微信小程序类似，期望kbone能支持其他平台，毕竟小程序这个概念也是微信提出来并实现的，对吧
