### ISSUE TITLE
canvas 初始化节点获取不到

### ISSUE THREAD

**Issue by hucheng91** [wechat-miniprogram/kbone#43]
```html
 <canvas id="canvas" style="width: 100%; height: 100%; position: absolute" type="2d"></canvas>

    wx.createSelectorQuery()
      .select('#canvas')
      .fields({
        node: true,
        size: true
      })
      .exec(function (res) { self.initCanvas(res) })
```

**Comment by JuneAndGreen** [comment]
因为canvas在某个自定义组件上，不传入实例是获取不到的，所以如果是获取 context 可以这么做：https://github.com/wechat-miniprogram/kbone/blob/fdfa985e4568aa04e64e74aebbd353b7118be2c1/examples/demo3/src/index/App.vue#L494

具体文档参考：https://github.com/wechat-miniprogram/kbone/blob/develop/docs/domextend.md

**Comment by JuneAndGreen** [comment]
如果是想要获取 node 对象或者其他的一些信息，可以这样获取对应的 NodesRef 对象然后进行操作：https://github.com/wechat-miniprogram/kbone/blob/develop/docs/domextend.md#domgetnodesref

这个 NodesRef 对象就是 wx.createSelectorQuery().select() 返回的对象，对应的文档是：https://developers.weixin.qq.com/miniprogram/dev/api/wxml/NodesRef.html
