### ISSUE TITLE
被miniprogram-element 包裹的内容无法被 createSelectorQuery select到

### ISSUE THREAD

**Issue by guanyx** [wechat-miniprogram/kbone#45]
示例代码
```js
      window.$$createSelectorQuery().select('.h5-body').boundingClientRect((rect) => {
        // 可以
      }).exec()

      window.$$createSelectorQuery().select('#app').boundingClientRect((rect) => {
        // rect 是null
      }).exec()
```

wxml结构
![image](https://user-images.githubusercontent.com/4861550/69133980-c531e900-0af1-11ea-8788-1aea6f5d8f20.png)

不管是用wx.createSelectorQuery 还是 window.$$createSelectorQuery 结果都是一样

**Comment by JuneAndGreen** [comment]
因为垮了 shadow tree，所以选择时得用 >>> 选择器，比如 `select('.h5-body >>> #app')` 这样。不过这里有个更便捷的方式，可以直接获取到 nodesRef 对象，不需要自己 createSelectorQuery 再 select：https://github.com/wechat-miniprogram/kbone/blob/develop/docs/domextend.md#domgetnodesref

![image](https://user-images.githubusercontent.com/7931744/69143576-41cdc300-0b04-11ea-97e9-64377be57282.png)
