### ISSUE TITLE
关于UI组件库

### ISSUE THREAD

**Issue by killdada** [wechat-miniprogram/kbone#48]
比如vant本身有小程序和web端的版本，能否兼容小程序直接去找vant的小程序版本， web端找vant的web版本？

**Comment by TomVista** [comment]
reduec-loader可以实现,具体例子,在模板中有 以vue为例=> kbone-template-vue/src/home/Index.vue

**Comment by killdada** [comment]
check-reduce reduce-loader只是针对web端显示，小程序端过滤掉了。尝试在demo10 自定义组件里面增加引用vant-webapp小程序版本失败。而且这种尝试还是需要写二分引入的，如果可以包装一下，用户使用只是简单的import会更好点

**Comment by JuneAndGreen** [comment]
目前 kbone-ui 正在开发中，初版将近完成，这是兼容小程序和h5两端的，到时候可以使用哈。

**Comment by killdada** [comment]
嗯，看了下vant的web端和小程序版本，虽然大多看起来一样，但是实际的参数肯定是有区别的，所以这样的考虑就没多大必要了。期待组件的完成，之前的mpvue的bug还有特性缺少有很多，目前简单试了kbone之前的一些mpvue问题没有了,很赞，具体就等到实践在看，期待kbone生态的一步步完善。
