### ISSUE TITLE
使用alloyFinger长按手势，触发事件时由于touches为null引起length属性读取报错

### ISSUE THREAD

**Issue by kokoFE** [wechat-miniprogram/kbone#50]
在浏览器中e.touches返回的是一个类数组对象，始终有length属性。
由于miniprogram-render中Event类进行了如下处理：

    this.$_touches = null
    ...
    if (options.touches && options.touches.length) {

            this.$_touches = options.touches.map(touch => ({...touch, target: options.target}))

            this.$$checkTargetTouches()
    }

很明显当touches长度为0时 this.$_touches 不会被处理成一个空数组。
changedTouches、 targetTouches可能也有类似情况，希望可以做出相关修改，避免冲突。

**Comment by JuneAndGreen** [comment]
已做出相关修复，可以尝试下这个包：miniprogram-render@0.5.13
