### ISSUE TITLE
React写的组件,H5端支持input元素的focus/blur事件,而编译成小程序不起作用

### ISSUE THREAD

**Issue by songzhuorong18** [wechat-miniprogram/kbone#54]

**Comment by songzhuorong18** [comment]
import React from 'react'
import ReactDOM from 'react-dom'
class Counter extends React.Component {
  constructor (props) {
    super(props);
    this.state = { value: 'test' };
  }

  printInfo (info) {
    console.log("!!!!!!", info)
  }


  render () {
    return (
      <div>
        <label for="male">测试</label>
        <input type="text" name="sex" id="male" value={this.state.value} onFocus={this.printInfo.bind(this, 'focus')}
               onBlur={this.printInfo.bind(this, 'blur')}/>
      </div>)
  }
}
export default function createApp() {
  const container = document.createElement('div')
  container.id = 'app'
  document.body.appendChild(container)
  ReactDOM.render(<Counter/>, container)
}

**Comment by songzhuorong18** [comment]
focus和blur事件在浏览器中能触发,编译成小程序以后无法触发

**Comment by JuneAndGreen** [comment]
已在 miniprogram-render@0.7.0 和 miniprogram-element@0.7.0 兼容修复

**Comment by JuneAndGreen** [comment]
已补充 demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo16
