### ISSUE TITLE
 t.setAttributeNS is not a function

### ISSUE THREAD

**Issue by zhouliangshun** [wechat-miniprogram/kbone#57]
可以给 Element加一个这个方法，现在没有这个方法报错。

**Comment by DYngng** [comment]
n.getElementsByName is not a function; dom 操作现在是不支持嘛

**Comment by DYngng** [comment]
n.getElementsByName is not a function; document 部分属性不支持嘛

**Comment by zhouliangshun** [comment]
嗯，最好时能进行mock，因为很多第三方库可能调用到了，除非完全用你们的框架，但是这样那还不如自己用小程序开发了。

**Comment by JuneAndGreen** [comment]
miniprogram-render@0.6.0 已追加 setAttributeNS，使用 setAttribute 进行兼容。document.getElementsByName 也已在此版本支持。

如果遇到一些标准 api 但是官方未能及时支持的情况，也可以考虑使用扩展接口自行兼容：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E6%89%A9%E5%B1%95-dom-bom-%E5%AF%B9%E8%B1%A1%E5%92%8C-api
