### ISSUE TITLE
使用<canvas>绘制不出东西

### ISSUE THREAD

**Issue by saoraozhe3hao** [wechat-miniprogram/kbone#61]
`<canvas class="progress" canvas-id="canvasProgress"></canvas>`

     const ctx =  wx.createCanvasContext('canvasProgress');
    context.setStrokeStyle("#00ff00")
    context.setLineWidth(5)
    context.rect(0, 0, 200, 200)
    context.stroke()
    context.setStrokeStyle("#ff0000")
    context.setLineWidth(2)
    context.moveTo(160, 100)
    context.arc(100, 100, 60, 0, 2 * Math.PI, true)
    context.moveTo(140, 100)
    context.arc(100, 100, 40, 0, Math.PI, false)
    context.moveTo(85, 80)
    context.arc(80, 80, 5, 0, 2 * Math.PI, true)
    context.moveTo(125, 80)
    context.arc(120, 80, 5, 0, 2 * Math.PI, true)
    context.stroke()
    context.draw()

**Comment by JuneAndGreen** [comment]
因为他在组件中，需要传入组件实例，有个更简单的方法可以快速拿到 context：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getcontext，也可以走 selectorQuery/nodesRef 的方式来获取 context：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getnodesref
