### ISSUE TITLE
使用 $$createSelectorQuery 查询不到东西

### ISSUE THREAD

**Issue by saoraozhe3hao** [wechat-miniprogram/kbone#62]
`   <div id="test"/>           `

 window.addEventListener('wxload', (query: any) => {
                window.$$createSelectorQuery()
                    .select('#test')
                    .fields({
                        node: true
                    })
                    .exec((res)=>{
                        // res == [null]
                    })
            });

**Comment by JuneAndGreen** [comment]
window.$$createSelectorQuery  相当于 wx.createSelectorQuery，所在的 context 是页面实例，跨自定义组件得使用 `>>>` 选择器，比如 `select('.h5-body >>> #xxx')` 的方式，不过有个更简单的方式可以直接拿到 nodesRef 对象：https://wechat-miniprogram.github.io/kbone/docs/domextend/#dom-getnodesref
