### ISSUE TITLE
dist/mp/node_modules 应该是多余的？

### ISSUE THREAD

**Issue by zilong-thu** [wechat-miniprogram/kbone#64]
![image](https://user-images.githubusercontent.com/5078580/71715841-b7d88000-2e4d-11ea-8aa2-f0679d96aaa3.png)

miniprogram-element、miniprogram-render 已经随着 miniprogram_npm 目录一起放到了dist/mp 目录下，node_modules 应该就不需要放进去了（我测试了一下，直接删除 dist/mp/node_modules 目录，运行正常）。

这个是否可以删除？感觉挺影响性能的。

**Comment by zilong-thu** [comment]
目前找到了不更改 mp-webpack-plugin 插件源码来解决此问题的一个方案：

在 miniprogram.config.js 里的 projectConfig 里配置属性：

```
    projectConfig: {
        packOptions: {
            ignore: [{
                type: 'folder',
                value: 'node_modules'
            }],
        }
    }
```

**Comment by JuneAndGreen** [comment]
1、这个属于小程序的依赖，走的 npm 构建。而 npm 构建就是先装到 node_modules 再构建成 miniprogram_npm 目录下的，如果后续你要维护升级依赖版本的话，就不能干掉。
2、node_modules 不影响性能，它本身就会被工具忽略不会算入小程序包也不会被上传的。
