### ISSUE TITLE
$$getNodesRef() 获取不到canvas 实例

### ISSUE THREAD

**Issue by saoraozhe3hao** [wechat-miniprogram/kbone#66]
`<canvas canvas-id="source" id="source"></canvas>`

                document.querySelector('#source').$$getNodesRef().then(nodesRef => {
                    nodesRef.node(res => {
                       console.log(res.node);  // 这里res.node == null
                    }).exec()
                })

**Comment by saoraozhe3hao** [comment]
`<canvas>` 加上type后，能得到实例了

**Comment by JuneAndGreen** [comment]
是的，通过 node 方法获取，需要指定 type。文档好像没有说明，我让相关同学帮忙在文档里补充一下。
