### ISSUE TITLE
React 事件机制

### ISSUE THREAD

**Issue by YikaJ** [wechat-miniprogram/kbone#70]
在看 kbone 源码，发现很多事件会使用 callSimpleEvent 进行调用。发现它和 callEvent 的区别是，通过减少冒泡来加快性能。但这个和 React 的事件机制似乎不太搭，因为 React 会将事件都挂载到 document 上，等待事件冒泡来触发。

比如 input 组件的 focus / blur 事件，因为使用了 callSimpleEvent，导致 React 上无法通过 onFocus 绑定事件，改为 callEvent 就可以了。
https://github.com/wechat-miniprogram/kbone/blob/87f9df5522640cd983afb321408acf50cc1e7342/packages/miniprogram-element/src/component/input.js#L123

想知道 kbone 后续该如何适配 React 这里的类似问题。

**Comment by YikaJ** [comment]
再和 remax 比对后，发现 remax 会有一个 processProps 的函数，用于将事件都挂载到 document 上。而 kbone 似乎并没有这个操作。

**Comment by JuneAndGreen** [comment]
已在 miniprogram-render@0.7.0 和 miniprogram-element@0.7.0 兼容修复

**Comment by YikaJ** [comment]
@JuneAndGreen 
我看到了你们的 commit 了，onFocus / onChange 等确实生效了。
但是仍有部分特殊的事件，似乎并没有处理。

例如 input 的 bind:confirm 事件，在手机里对应的是手机键盘的完成键，在 web 对应的应该是回车键，这些会如何兼容呢？

**Comment by JuneAndGreen** [comment]
@YikaJ confirm 事件我记一下，后续看看能不能也补充上去

**Comment by JuneAndGreen** [comment]
@YikaJ confirm 事件不在 React 的标准事件里，所以建议使用 addEventListener 来添加。或者也可以尝试使用 Preact，它没有这个限制，而且更轻量。
