### ISSUE TITLE
canvas转换为图片不生效

### ISSUE THREAD

**Issue by cuiyuanguang** [wechat-miniprogram/kbone#76]
生成的canvas使用wx.canvasToTempFilePath不能进入success或者fail任意一个函数

**Comment by cuiyuanguang** [comment]
救救孩子

**Comment by JuneAndGreen** [comment]
使用了 kbone 的情况？是的话方便给一下简单能复现的 demo 么？我这边定位一下是什么问题。

**Comment by cuiyuanguang** [comment]
已解决 canvasToTempFilePath 第二个参数传 this.$el._wxComponent 就好了
