### ISSUE TITLE
自行构建的ts+react打包压缩后主包仍超出2mb的限制

### ISSUE THREAD

**Issue by zzxqd** [wechat-miniprogram/kbone#77]
![图片](https://user-images.githubusercontent.com/23022401/72787637-42511a00-3c6b-11ea-8a31-fed78b1bf95c.png)
![图片](https://user-images.githubusercontent.com/23022401/72787791-8d6b2d00-3c6b-11ea-9bb9-20ff40cb1469.png)
不知道是否是我构建的问题（另祝新年快乐）

**Comment by JuneAndGreen** [comment]
是业务代码过大引起的么？

如果是业务代码的话，可以尝试拆分多页，然后使用小程序自身的分包功能：https://wechat-miniprogram.github.io/kbone/docs/config/#generate-subpackages

如果是非业务代码的话，猜测有可能打包配置不太对，可以参考一下这个demo的配置：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo16
