### ISSUE TITLE
切换TabBar的时候页面无法加载

### ISSUE THREAD

**Issue by 286810** [wechat-miniprogram/kbone#79]
参考demo配置了一下，TabBar正常显示但切换的时候页面无法加载
![image](https://user-images.githubusercontent.com/5809508/73905114-3acf7900-48d9-11ea-8d47-9f08a8c96c2c.png)
上图是第一次打开时，正常加载home页
![image](https://user-images.githubusercontent.com/5809508/73905139-4a4ec200-48d9-11ea-8ed0-0acdf9417444.png)
切换到我的后，没有加载我的页面，控制台只显示
![image](https://user-images.githubusercontent.com/5809508/73904078-df4fbc00-48d5-11ea-9240-db9bd7356330.png) ，没有加载我的页面
这是 miniprogram.config.js 里的配置
![image](https://user-images.githubusercontent.com/5809508/73905067-14114280-48d9-11ea-84a3-c36efe1d5d7e.png)
这是打包出来的 app.json
![image](https://user-images.githubusercontent.com/5809508/73905052-022f9f80-48d9-11ea-8fa4-301a417cefe0.png)

各位老铁，这是为啥呀？

**Comment by 286810** [comment]
用 kbone-template-vue 创建的项目，是少了配置什么还是什么原因呢？

**Comment by JuneAndGreen** [comment]
方便贴一下小程序端的 webpack 配置么？

**Comment by 286810** [comment]
> 方便贴一下小程序端的 webpack 配置么？

已经引入了
![image](https://user-images.githubusercontent.com/5809508/74230077-985f2d80-4cfe-11ea-90f7-2a247d2ff51e.png)

**Comment by 286810** [comment]
还需要配置什么吗？

**Comment by JuneAndGreen** [comment]
页面使用了 vue-router，里面没有处理 / 这个 path，而 tabbar 页面目前默认进去的 path 是 /，导致页面里的 vue-router 没有匹配出 router-view，因而看起来像页面没有装载。

给对应页面的 router 配置加下 {path: '/', redirect: '/test/search'}, 即可。

后续这边会支持定制进去 tabbar 页面的默认 path，不过目前的话就需要自己处理了。
