### ISSUE TITLE
[Bug Report] 引入 vant 组件库后，小程序端UI 显示不正确，但 web端可以正常显示

### ISSUE THREAD

**Issue by ly526** [wechat-miniprogram/kbone#82]
您好，打扰了，是否可以帮忙看下一个 kbone 的一个问题

## 问题描述：
引入了 vant 组件库之后，
其中 yarn web 显示是正常的，但 小程序端 UI 显示异常，复现代码库：https://github.com/ly526/kbone-template-vue

```shell
npm i
npm run mp
npm run web
```

## 截图演示：
小程序（轮播图 UI 样式没有生效）：
![image](https://user-images.githubusercontent.com/61106776/74601961-c23d9900-50de-11ea-9306-e0bd42e11b35.png)

web 端（正常）
![image](https://user-images.githubusercontent.com/61106776/74601978-003abd00-50df-11ea-8f5d-ea54a8dc17c1.png)

**Comment by JuneAndGreen** [comment]
这个组件内部使用了 getBoundingClientRect，在小程序端无法兼容成同步接口，故无法直接使用。可以使用 kbone-ui 中的 KSwiper 和 KSwiperItem 来代替。
