### ISSUE TITLE
能提供一个云开发官方模版吗？

### ISSUE THREAD

**Issue by ACChe** [wechat-miniprogram/kbone#84]

**Comment by JuneAndGreen** [comment]
已提供demo：https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo19
和文档：https://wechat-miniprogram.github.io/kbone/docs/guide/advanced.html#%E4%BA%91%E5%BC%80%E5%8F%91

**Comment by ACChe** [comment]
@JuneAndGreen Thanks very much!
