### ISSUE TITLE
rem在h5端计算不准确？

### ISSUE THREAD

**Issue by wanghongjiao** [wechat-miniprogram/kbone#85]
![image](https://user-images.githubusercontent.com/23325540/75009420-9b53de00-54b5-11ea-831f-f5749587adfd.png)
![image](https://user-images.githubusercontent.com/23325540/75009467-b888ac80-54b5-11ea-9d1c-4f53f0dcdd07.png)
![image](https://user-images.githubusercontent.com/23325540/75009486-c4746e80-54b5-11ea-9207-81cff498c581.png)

**Comment by JuneAndGreen** [comment]
demo 中 h5  的计算方式仅供参考，你可以使用你熟悉的任意一种方式。只要小程序能够对齐即可。kbone 主要处理如何让其跑到小程序上，并不会对原有 h5 代码做任何处理。
